# Generated by Django 5.1.7 on 2025-04-28 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.CharField(max_length=25)),
                ('codigo_insumo', models.IntegerField()),
                ('descricao_do_insumo', models.TextField()),
                ('unidade', models.CharField(max_length=3)),
                ('origem_de_preco', models.CharField(max_length=3)),
                ('AC', models.FloatField(blank=True, default=0, null=True)),
                ('AL', models.FloatField(blank=True, default=0, null=True)),
                ('AP', models.FloatField(blank=True, default=0, null=True)),
                ('AM', models.FloatField(blank=True, default=0, null=True)),
                ('BA', models.FloatField(blank=True, default=0, null=True)),
                ('CE', models.FloatField(blank=True, default=0, null=True)),
                ('DF', models.FloatField(blank=True, default=0, null=True)),
                ('ES', models.FloatField(blank=True, default=0, null=True)),
                ('GO', models.FloatField(blank=True, default=0, null=True)),
                ('MA', models.FloatField(blank=True, default=0, null=True)),
                ('MT', models.FloatField(blank=True, default=0, null=True)),
                ('MS', models.FloatField(blank=True, default=0, null=True)),
                ('MG', models.FloatField(blank=True, default=0, null=True)),
                ('PA', models.FloatField(blank=True, default=0, null=True)),
                ('PB', models.FloatField(blank=True, default=0, null=True)),
                ('PR', models.FloatField(blank=True, default=0, null=True)),
                ('PE', models.FloatField(blank=True, default=0, null=True)),
                ('PI', models.FloatField(blank=True, default=0, null=True)),
                ('RJ', models.FloatField(blank=True, default=0, null=True)),
                ('RN', models.FloatField(blank=True, default=0, null=True)),
                ('RS', models.FloatField(blank=True, default=0, null=True)),
                ('RO', models.FloatField(blank=True, default=0, null=True)),
                ('RR', models.FloatField(blank=True, default=0, null=True)),
                ('SC', models.FloatField(blank=True, default=0, null=True)),
                ('SP', models.FloatField(blank=True, default=0, null=True)),
                ('SE', models.FloatField(blank=True, default=0, null=True)),
                ('TO', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
    ]
