# Generated by Django 5.1.7 on 2025-04-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composicoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=255)),
                ('codigo_composicao', models.IntegerField(default=0, null=True)),
                ('tipo_item', models.CharField(max_length=100, null=True)),
                ('codigo_item', models.IntegerField(default=0, null=True)),
                ('descricao', models.TextField()),
                ('unidade', models.CharField(max_length=55)),
                ('coeficiente', models.FloatField(default=0, null=True)),
            ],
        ),
    ]
