### Criar um registro de teste no Supabase
POST http://localhost:8000/teste
Content-Type: application/json

{
    "nome": "Michael Jackson",
    "escolaridade": "Ensino Fundamental"
}

### Listar todos os registros de teste no Supabase
GET http://localhost:8000/teste
Content-Type: application/json

### Buscar um registro de teste por ID no Supabase
GET http://localhost:8000/teste/1
Content-Type: application/json

### Deletar um registro de teste por ID no Supabase
DELETE http://localhost:8000/teste/1
Content-Type: application/json

### Importar composições da planilha SINAPI (aba CSD) para duas tabelas: composicoes e composicoes_estados
POST http://localhost:8000/composicoes/importar